# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: 소개
    url: /
    identifier: about
    weight: 10
  - name: 프로필
    parent: about
    url: /profile/
    weight: 10
  - name: 연락
    parent: about
    url: /contact/
    weight: 10

  - name: Skills
    url: /#skills
    identifier: skills
    weight: 11
  - name: Development
    parent: skills
    url: skills/development/
    weight: 11
  - name: Lifestyle
    parent: skills
    url: skills/life/
    weight: 11

  - name: Projects
    url: /#projects
    identifier: projects
    weight: 12
  - name: Fullstack
    parent: projects
    url: projects/fullstack/
    weight: 12
  - name: Backend
    parent: projects
    url: projects/backend/
    weight: 12

  - name: Postings
    url: /#postings
    identifier: postings
    weight: 13
  - name: Study
    parent: postings
    url: postings/study/
    weight: 13
  - name: Diary
    parent: postings
    url: postings/diary/
    weight: 13

  - name: Others
    url: /#others
    identifier: others
    weight: 14
  - name: Etc...
    parent: others
    url: others/etc/
    weight: 14
  - name: Random
    parent: others
    url: others/random/
    weight: 14